Algoritmo "variaveis"
// Disciplina   : tipos de dados
// Professor   : Antonio Carlos Nicolodi 
// Descrição   :  aprender os tipos variaveis mais usados
// Autor(a)    : jefferson farias da silva
// Data atual  : 28/07/2020
Var
// Seção de Declarações das variáveis 
// primeiro nome
// segundo nome
// idade
// cidade
// endereço

    primeiroName, segundoName, cidade, endereco: caractere,
    idade: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo